/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author M Alfan R
 */
public class menumahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form menumahasiswa
     */
    public menumahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iconprofil = new javax.swing.JButton();
        iconlihatkata = new javax.swing.JButton();
        icontopcontributor = new javax.swing.JButton();
        iconlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Menuprofil = new javax.swing.JPanel();
        profilmahasiswa = new javax.swing.JLabel();
        namaa = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        nimm = new javax.swing.JTextField();
        tgllahir = new javax.swing.JLabel();
        tgllahirr = new javax.swing.JTextField();
        prodi = new javax.swing.JTextField();
        prodii = new javax.swing.JLabel();
        angkatann = new javax.swing.JTextField();
        angkatan = new javax.swing.JLabel();
        usernamee = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        passwordd = new javax.swing.JPasswordField();
        konfirmm = new javax.swing.JPasswordField();
        konfirm = new javax.swing.JLabel();
        gantipassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(116, 185, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        iconprofil.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        iconprofil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Webp.net-resizeimage (7).png"))); // NOI18N
        iconprofil.setText("Profil mahasiswa");
        iconprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconprofilActionPerformed(evt);
            }
        });

        iconlihatkata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Webp.net-resizeimage (3).png"))); // NOI18N
        iconlihatkata.setText("Lihat kata");
        iconlihatkata.setIconTextGap(10);
        iconlihatkata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconlihatkataActionPerformed(evt);
            }
        });

        icontopcontributor.setText("Top Contributor");

        iconlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Webp.net-resizeimage (5).png"))); // NOI18N
        iconlogout.setText("Log out");
        iconlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconlogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Webp.net-resizeimage (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("iPedia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iconlihatkata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iconprofil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icontopcontributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iconlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(122, 122, 122)
                .addComponent(iconprofil)
                .addGap(18, 18, 18)
                .addComponent(iconlihatkata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(icontopcontributor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(iconlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 630));

        jPanel3.setBackground(new java.awt.Color(56, 173, 169));
        jPanel3.setLayout(new java.awt.CardLayout());

        Menuprofil.setBackground(new java.awt.Color(0, 153, 153));
        Menuprofil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        profilmahasiswa.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        profilmahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        profilmahasiswa.setText("PROFIL MAHASISWA");

        namaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaaActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama");

        nim.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        nim.setForeground(new java.awt.Color(255, 255, 255));
        nim.setText("NIM");

        tgllahir.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        tgllahir.setForeground(new java.awt.Color(255, 255, 255));
        tgllahir.setText("Tanggal Lahir");

        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });

        prodii.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        prodii.setForeground(new java.awt.Color(255, 255, 255));
        prodii.setText("Program Studi");

        angkatann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkatannActionPerformed(evt);
            }
        });

        angkatan.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        angkatan.setForeground(new java.awt.Color(255, 255, 255));
        angkatan.setText("Angkatan");

        usernamee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameeActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");

        password.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        konfirm.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        konfirm.setForeground(new java.awt.Color(255, 255, 255));
        konfirm.setText("Konfirmasi Password");

        gantipassword.setBackground(new java.awt.Color(255, 255, 255));
        gantipassword.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        gantipassword.setForeground(new java.awt.Color(255, 255, 255));
        gantipassword.setText("Ganti Password");

        javax.swing.GroupLayout MenuprofilLayout = new javax.swing.GroupLayout(Menuprofil);
        Menuprofil.setLayout(MenuprofilLayout);
        MenuprofilLayout.setHorizontalGroup(
            MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuprofilLayout.createSequentialGroup()
                .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuprofilLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(nama))
                    .addGroup(MenuprofilLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(nim))
                    .addGroup(MenuprofilLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prodii)
                                .addComponent(tgllahir)
                                .addComponent(namaa)
                                .addComponent(nimm)
                                .addComponent(tgllahirr)
                                .addComponent(prodi)
                                .addComponent(angkatann, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addComponent(angkatan))
                        .addGap(77, 77, 77)
                        .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konfirm)
                            .addComponent(usernamee, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username)
                            .addComponent(password)
                            .addComponent(passwordd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(konfirmm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gantipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuprofilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profilmahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        MenuprofilLayout.setVerticalGroup(
            MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuprofilLayout.createSequentialGroup()
                .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuprofilLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nimm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tgllahir)
                            .addComponent(username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernamee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgllahirr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodii)
                            .addComponent(password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MenuprofilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilmahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(angkatan)
                .addGap(14, 14, 14)
                .addGroup(MenuprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(angkatann, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konfirmm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(gantipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanel3.add(Menuprofil, "card2");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 11, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconlihatkataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconlihatkataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconlihatkataActionPerformed

    private void iconprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconprofilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconprofilActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiActionPerformed

    private void usernameeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameeActionPerformed

    private void angkatannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkatannActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angkatannActionPerformed

    private void iconlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconlogoutActionPerformed
        // TODO add your handling code here:
         int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar?", "PERINGATAN", dialogBtn);
        
        if (dialogResult==0) {
            loginadmin form = new loginadmin();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            this.dispose();
        } else {
            
        }
    }//GEN-LAST:event_iconlogoutActionPerformed

    private void namaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_namaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menumahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menumahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menumahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menumahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menumahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menuprofil;
    private javax.swing.JLabel angkatan;
    private javax.swing.JTextField angkatann;
    private javax.swing.JButton gantipassword;
    private javax.swing.JButton iconlihatkata;
    private javax.swing.JButton iconlogout;
    private javax.swing.JButton iconprofil;
    private javax.swing.JButton icontopcontributor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel konfirm;
    private javax.swing.JPasswordField konfirmm;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namaa;
    private javax.swing.JLabel nim;
    private javax.swing.JTextField nimm;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordd;
    private javax.swing.JTextField prodi;
    private javax.swing.JLabel prodii;
    private javax.swing.JLabel profilmahasiswa;
    private javax.swing.JLabel tgllahir;
    private javax.swing.JTextField tgllahirr;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamee;
    // End of variables declaration//GEN-END:variables
}
